-- SUPABASE POSTGRESQL SCHEMA

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. URLs Table
CREATE TABLE IF NOT EXISTS urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_url TEXT NOT NULL,
    short_code TEXT UNIQUE NOT NULL,
    click_count INTEGER DEFAULT 0,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Clicks Table
CREATE TABLE IF NOT EXISTS url_clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_id BIGINT NOT NULL REFERENCES urls(id) ON DELETE CASCADE,
    ip_address TEXT,
    user_agent TEXT,
    referrer TEXT,
    device_type TEXT,
    browser TEXT,
    os TEXT,
    clicked_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Enable Row Level Security (RLS) - Optional but recommended
-- 6. RPC for atomic increments
CREATE OR REPLACE FUNCTION increment_click_count(target_url_id BIGINT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    UPDATE urls
    SET click_count = click_count + 1
    WHERE id = target_url_id;
END;
$$;
-- For this simple project, we use the service role key which bypasses RLS.
-- If you want to use public keys, you would need to define policies.

-- 5. Performance Indexes
CREATE INDEX IF NOT EXISTS idx_urls_short_code ON urls (short_code);
CREATE INDEX IF NOT EXISTS idx_urls_user_id ON urls (user_id);
CREATE INDEX IF NOT EXISTS idx_clicks_url_id ON url_clicks (url_id);
CREATE INDEX IF NOT EXISTS idx_clicks_clicked_at ON url_clicks (clicked_at);
